version: "3.8"

services:
  postgres:
    image: postgres:18.0-alpine
    container_name: movie-postgres
    environment:
      POSTGRES_USER: deepak
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: moviesdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # server:
  #   build: ./server
  #   image: go-backend:1.0
  #   container_name: go-backend
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./server:/app
  #   environment:
  #     DB_HOST: postgres
  #     DB_USER: deepak
  #     DB_PASS: password123
  #     DB_NAME: moviesdb
  #   depends_on:
  #     - postgres

volumes:
  pgdata: {}
